version: '3.1'

services:

  db:
    image: postgres:12.3
    restart: always
    env_file: .env.test
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../volumes_test/postgres:/var/lib/postgresql/data

  backend:
    image: auto-dq-backend:local
    env_file: .env.test
    volumes:
      - ${PWD}:/usr/src/app
    command: ["./wait-for-postgres.sh", "./entrypoint-test.sh"]
